version: "3.8"

    

services:
  flask-tor-1:
    image: "flask-tor"
    hostname: "flask-tor-1"
    container_name: "flask-tor-1"
    user: tor
    labels:
      - com.centurylinklabs.watchtower.enable=true


    build:
      context: .
      dockerfile: "./Dockerfile"  
    
    

    volumes:
       - "./tor_keys:/var/lib/tor/hidden_service"
     
    
      
    networks:
      internet-network:
        ipv4_address: 10.10.2.2

      
    ports:
      - 8080:8080





    restart: always
    
    command: sh -c 'echo "&root&" | su -c "chown -R tor:tor /var/lib/tor/ && chmod -R u=rwx,g=s,o= /var/lib/tor/hidden_service/" root > /dev/null 2>&1 && echo "Configuring Tor" & tor & sleep 2 && printf "Onion Site Will Be Up in 30 Seconds\nOnion address -> " && cat /var/lib/tor/hidden_service/hostname &&  echo "&flaskuser&" |  su -c "gunicorn -b 0.0.0.0:8080  --pythonpath ./app -w 2  --threads 3 main:app" flaskuser '
    

    
    depends_on:
      - watchtower



  watchtower:
    image: "containrrr/watchtower"
    hostname: "watchtower"
    container_name: "watchtower"


    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


    environment:
      WATCHTOWER_SCHEDULE: "0 00 00 * * *"
      WATCHTOWER_CLEANUP: "true"
      ATCHTOWER_DEBUG: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      




networks:
 
  internet-network:
    name: "flasktor-internet-network"
    
    driver: ipvlan
    driver_opts:
      parent: enp2s0f0
      ipvlan_mode: l3
    
    
    ipam:
      config:
        - subnet: 10.10.2.0/24
          gateway: 10.10.2.1
               
    

